version: '1.0'

services:
  db:
    image: postgres:16.0-alpine
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  liquid:
    image: liquibase/liquibase
    container_name: liquid
    depends_on:
      db:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${PG_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${PG_PASSWORD}
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/${PG_DATABASE}
      LIQUIBASE_LOG_LEVEL: WARNING
    volumes:
      - ./src/main/resources/db/changelog/:/liquibase/changelog
      - ./src/main/resources/db/db.changelog-master.xml:/liquibase/db.changelog-master.xml
    command: --changelog-file db.changelog-master.xml update

  app-build-start:
    container_name: app-build-start
    profiles:
      - build
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  pg-data:

