spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${PG_IP}:${PG_PORT}/${PG_DATABASE}
        username: ${PG_USERNAME}
        password: ${PG_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: ${APP_PORT}

jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 30m